when:
  - event: [push, manual]

labels:
  platform: windows/amd64

steps:
  - name: build
    image: powershell
    commands:
      - |
        if (!(Get-Command rustc -ErrorAction SilentlyContinue)) {
          echo "Installing Rust..."
          iex ((New-Object System.Net.WebClient).DownloadFile('https://win.rustup.rs/x86_64'));
          rustup-init.exe -y
        }

      - rustc --version
