when:
  - event: [push, manual]

labels:
  platform: windows/amd64

steps:
  - name: install rust
    image: powershell
    commands:
      - |
        $ProgressPreference = 'SilentlyContinue'

        if (!(Get-Command rustc -ErrorAction SilentlyContinue)) {
          echo "Installing Rust..."
          Invoke-WebRequest -Uri https://win.rustup.rs -OutFile rustup-init.exe
          ./rustup-init.exe -y --toolchain nightly
        }

  - name: build
    image: powershell
    commands:
      - rustup default nightly
      - cargo build --release
