when:
  - event: [push, manual]
    platform: linux/amd64

steps:
  - name: build
    image: clux/muslrust:nightly-2024-08-24
    environment:
      RUSTFLAGS: "-C target-feature=+crt-static"
    commands:
      - sleep 5
      - exit 1
      #- apt-get -y update
      #- apt-get -y install pkg-config libssl-dev build-essential protobuf-compiler
      #- cargo build --release --target x86_64-unknown-linux-musl
