skip_clone: true

steps:
  - name: build
    image: curlimages/curl:8.11.0
    commands:
      - echo $CI_PIPELINE_STARTED
  - name: notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: >
        {{#success build.status}}
          Pipeline [#{{build.number}}]({{build.link}}) (linux/amd64) of branch `{{build.branch}}` passed in {{since build.started}}
        {{else}}
          Pipeline [#{{build.number}}]({{build.link}}) (linux/amd64) of branch `{{build.branch}}` failed in {{since build.started}}
        {{/success}}

depends_on:
  - build-linux

runs_on: [ success, failure ]

# Linter wants a `when`, despite depends_on
when:
  - repo: ArmchairDevelopers/Maxima
