skip_clone: true

steps:
  - name: build
    image: curlimages/curl:8.11.0
    commands:
      - CURRENT_TIME=$(date +%s)
      - ELAPSED_TIME=$(($CURRENT_TIME - $CI_PIPELINE_STARTED))
      - ELAPSED_TIME_STR=$(date -u -d @$ELAPSED_TIME +'%Mm%Ss')
      - echo $CURRENT_TIME $CI_PIPELINE_STARTED $ELAPSED_TIME $ELAPSED_TIME_STR
      - |
        WEBHOOK_DATA=$(cat <<EOF
        {
          "embeds": [
            {
              "title": "Maxima CI",
              "description": "Pipeline [#${CI_PIPELINE_NUMBER}](${CI_PIPELINE_URL}) of branch \`${CI_COMMIT_BRANCH}\` passed in $ELAPSED_TIME_STR",
              "color": 8482378
            }
          ]
        }
        EOF
        )
      - echo $WEBHOOK_DATA

      - WEBHOOK_URL="https://discord.com/api/webhooks/${DISCORD_WEBHOOK_ID}/${DISCORD_WEBHOOK_TOKEN}"
      - "curl X POST -H \"Content-Type: application/json\" -d \"$WEBHOOK_DATA\" $WEBHOOK_URL"
    secrets: [ discord_webhook_id, discord_webhook_token ]

depends_on:
  - build-linux

runs_on: [ success, failure ]

# Linter wants a `when`, despite depends_on
when:
  - repo: ArmchairDevelopers/Maxima
